/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 m2.glb -t 
*/

import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'
import Badge from '../common/Badge'

type ActionName = 'stand' | 'tpose'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_7: THREE.SkinnedMesh
    Object_8: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    M_MarioBuilder_Body: THREE.MeshStandardMaterial
    M_MarioBuilder_Eye: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function M2(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/assets/models/m2.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)

  useEffect(()=>{ actions["stand"]?.play()},[actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" position={[1,-0.1,0]}>
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <group name="Builder_Mariofbx" rotation={[Math.PI / 2, 0, 0]} scale={1}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh receiveShadow castShadow name="Object_7" geometry={nodes.Object_7.geometry} material={materials.M_MarioBuilder_Body} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh receiveShadow castShadow name="Object_8" geometry={nodes.Object_8.geometry} material={materials.M_MarioBuilder_Eye} skeleton={nodes.Object_8.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/m2.glb')
