/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 plant.glb -t 
*/

import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'
import Badge from '../common/Badge'
import { motion } from "framer-motion-3d"

type ActionName = 'idle'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    plant: THREE.SkinnedMesh
    Bone: THREE.Bone
  }
  materials: {
    Piranha_Plant_Mat: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Plant(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/assets/models/plant.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)

  useEffect(()=>{ actions['idle']?.play()},[actions])

  return (
    <group ref={group} {...props} dispose={null}>
      
      <motion.group 
        whileTap={{scale: 1.1}}
        name="Scene">
        <group name="Armature" scale={0.5}>
          <primitive object={nodes.Bone} />
          <skinnedMesh receiveShadow castShadow name="plant" geometry={nodes.plant.geometry} material={materials.Piranha_Plant_Mat} skeleton={nodes.plant.skeleton} />
        </group>
      </motion.group>
      <Badge position={[0,0,0]} text="click!"/>
    </group>
  )
}

useGLTF.preload('/assets/models/plant.glb')
